use std::fs;
use std::path::Path;
use std::process::Command;

use crate::core::usb::UsbDevice;

/// GRUB protection status
#[derive(Debug, Clone, PartialEq)]
pub enum ProtectionStatus {
    Protected { locked_at: String, usb_uuid: String },
    Unprotected,
}

/// GRUBST config directory
const GRUBST_CONFIG_DIR: &str = "/etc/grub.d";
/// GRUBST superuser script (runs early to set superusers)
const SUPERUSER_SCRIPT: &str = "01_grubst_users";
/// GRUBST USB check script (runs to check for USB key)
const USB_CHECK_SCRIPT: &str = "02_grubst_usbcheck";
/// GRUBST state directory
const GRUBST_STATE_DIR: &str = "/var/lib/grubst";
/// GRUBST state file
const STATE_FILE: &str = "state.json";
/// GRUB readable directory (via $prefix in GRUB)
const GRUBST_GRUB_DIR: &str = "/boot/grub/grubst";
const GRUBST_MACHINE_CFG: &str = "machine.cfg";

/// Check current GRUB protection status
pub fn check_protection_status() -> Result<ProtectionStatus, String> {
    let state_path = Path::new(GRUBST_STATE_DIR).join(STATE_FILE);

    if !state_path.exists() {
        // Check if our scripts exist in /etc/grub.d/
        let superuser_path = Path::new(GRUBST_CONFIG_DIR).join(SUPERUSER_SCRIPT);
        if superuser_path.exists() {
            return Ok(ProtectionStatus::Protected {
                locked_at: "Unknown".to_string(),
                usb_uuid: "Unknown".to_string(),
            });
        }
        return Ok(ProtectionStatus::Unprotected);
    }

    // Read state file
    let content = fs::read_to_string(&state_path)
        .map_err(|e| format!("Failed to read state: {}", e))?;

    let state: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse state: {}", e))?;

    let locked = state
        .get("locked")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);

    if locked {
        let locked_at = state
            .get("locked_at")
            .and_then(|v| v.as_str())
            .unwrap_or("Unknown")
            .to_string();
        let usb_uuid = state
            .get("usb_uuid")
            .and_then(|v| v.as_str())
            .unwrap_or("Unknown")
            .to_string();

        Ok(ProtectionStatus::Protected {
            locked_at,
            usb_uuid,
        })
    } else {
        Ok(ProtectionStatus::Unprotected)
    }
}

/// Write the GRUB superuser configuration script
/// This creates /etc/grub.d/01_grubst_users which adds password protection
pub fn write_superuser_config(pbkdf2_hash: &str) -> Result<(), String> {
    let script_path = Path::new(GRUBST_CONFIG_DIR).join(SUPERUSER_SCRIPT);

    let script_content = format!(
        r#"#!/bin/sh
# ═══════════════════════════════════════════════════════════════
# GRUBST — Boot Security Hardening
# This script is auto-generated by GRUBST. DO NOT EDIT MANUALLY.
# It configures GRUB superuser authentication.
# ═══════════════════════════════════════════════════════════════

cat << 'GRUBST_USERS_EOF'
set superusers="grubst_admin"
password_pbkdf2 grubst_admin {hash}
GRUBST_USERS_EOF
"#,
        hash = pbkdf2_hash,
    );

    fs::write(&script_path, &script_content)
        .map_err(|e| format!("Failed to write superuser config: {}", e))?;

    // Make executable
    set_executable(&script_path)?;

    log::info!("GRUB superuser config written: {:?}", script_path);
    Ok(())
}

/// Write the GRUB USB check script
/// This creates /etc/grub.d/02_grubst_usbcheck which checks for the USB rescue key
pub fn write_usb_check_script(device: &UsbDevice, auth_token: &str) -> Result<String, String> {
    // Get the UUID of the USB partition
    let usb_uuid = crate::core::usb::get_partition_uuid(&device.path)
        .map_err(|e| format!("Failed to get USB UUID: {}", e))?;

    let script_path = Path::new(GRUBST_CONFIG_DIR).join(USB_CHECK_SCRIPT);

    // The GRUB script that checks for USB at boot time
    let script_content = format!(
        r#"#!/bin/sh
# ═══════════════════════════════════════════════════════════════
# GRUBST — USB Rescue Key Verification
# This script is auto-generated by GRUBST. DO NOT EDIT MANUALLY.
# It checks for the USB rescue key at boot time and unlocks
# GRUB if the correct key is found.
# ═══════════════════════════════════════════════════════════════

cat << 'GRUBST_USB_EOF'

# ── GRUBST USB Key Check ──
# Ensure necessary filesystem modules are loaded to read the USB
insmod part_msdos
insmod part_gpt
insmod fat

# Search for the USB rescue key by UUID
search --no-floppy --fs-uuid --set=grubst_usb_dev {usb_uuid}

if [ -n "$grubst_usb_dev" ]; then
    # USB found — check for the GRUBST marker file
    if [ -f ($grubst_usb_dev)/GRUBST_KEY ]; then
        set grubst_expected_token="{auth_token}"
        set grubst_usb_token=""
        set grubst_machine_fp_internal=""
        set grubst_machine_fp_usb=""

        if [ -f $prefix/grubst/machine.cfg ]; then
            source $prefix/grubst/machine.cfg
        fi

        if [ -f ($grubst_usb_dev)/.grubst/token.cfg ]; then
            source ($grubst_usb_dev)/.grubst/token.cfg
            if [ -f ($grubst_usb_dev)/.grubst/machine.cfg ]; then
                source ($grubst_usb_dev)/.grubst/machine.cfg
            fi
            if [ "$grubst_token" = "$grubst_expected_token" -a -n "$grubst_machine_fp_internal" -a "$grubst_machine_fp_usb" = "$grubst_machine_fp_internal" ]; then
                # UNSET superusers disables authentication entirely for this session
                unset superusers
                set grubst_unlocked="true"
            fi
        fi
    fi
fi

GRUBST_USB_EOF
"#,
        usb_uuid = usb_uuid,
        auth_token = auth_token,
    );

    fs::write(&script_path, &script_content)
        .map_err(|e| format!("Failed to write USB check script: {}", e))?;

    set_executable(&script_path)?;

    log::info!("GRUB USB check script written: {:?}", script_path);
    Ok(usb_uuid)
}

/// Modify existing GRUB menu entries to require authentication for editing
/// Normal boot remains unrestricted; editing/recovery requires superuser
pub fn protect_menu_entries() -> Result<(), String> {
    // GRUB's default behavior with superusers set:
    // - Booting a normal menu entry: NO password needed (--unrestricted)
    // - Editing a menu entry (pressing 'e'): password REQUIRED
    // - GRUB command line (pressing 'c'): password REQUIRED
    // - Recovery mode entries: password REQUIRED
    //
    // We need to ensure normal entries have --unrestricted flag
    // This is handled by modifying /etc/grub.d/10_linux

    let linux_script = Path::new(GRUBST_CONFIG_DIR).join("10_linux");
    if !linux_script.exists() {
        log::warn!("10_linux not found, skipping menu entry modification");
        return Ok(());
    }

    let content = fs::read_to_string(&linux_script)
        .map_err(|e| format!("Failed to read 10_linux: {}", e))?;

    // Check if already modified
    if content.contains("--unrestricted") {
        log::info!("10_linux already has --unrestricted flag");
        return Ok(());
    }

    let mut modified_content = content.clone();
    let mut modified = false;

    // Method 1: Patch the CLASS definition directly (Debian/Ubuntu style)
    if modified_content.contains("CLASS=\"--class gnu-linux --class gnu --class os\"") {
        modified_content = modified_content.replace(
            "CLASS=\"--class gnu-linux --class gnu --class os\"",
            "CLASS=\"--class gnu-linux --class gnu --class os --unrestricted\"",
        );
        modified = true;
    }

    // Method 2: Patch the printf/echo statements directly (Universal fallback)
    if !modified {
        modified_content = modified_content.replace(
            "printf \"menuentry '%s' ${CLASS} ",
            "printf \"menuentry '%s' ${CLASS} --unrestricted ",
        );
        modified_content = modified_content.replace(
            "echo \"menuentry '$(echo \"$title\" | grub_quote)' ${CLASS} ",
            "echo \"menuentry '$(echo \"$title\" | grub_quote)' ${CLASS} --unrestricted ",
        );
        modified = true;
    }

    if modified {
        fs::write(&linux_script, modified_content)
            .map_err(|e| format!("Failed to write patched 10_linux: {}", e))?;
        log::info!("10_linux patched with --unrestricted flag");
    } else {
        log::warn!("Could not find where to inject --unrestricted in 10_linux");
    }

    Ok(())
}

/// Run update-grub to regenerate grub.cfg
pub fn run_update_grub() -> Result<(), String> {
    log::info!("Running update-grub...");

    // Try update-grub first (Debian/Ubuntu)
    let output = Command::new("update-grub")
        .output();

    match output {
        Ok(o) if o.status.success() => {
            log::info!("update-grub completed successfully");
            return Ok(());
        }
        _ => {}
    }

    // Fallback: grub-mkconfig (Fedora/Arch)
    let output = Command::new("grub-mkconfig")
        .args(["-o", "/boot/grub/grub.cfg"])
        .output()
        .map_err(|e| format!("Failed to run grub-mkconfig: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("grub-mkconfig failed: {}", stderr));
    }

    log::info!("grub-mkconfig completed successfully");
    Ok(())
}

pub fn lock_grub(device: &UsbDevice, password: &str) -> Result<(), String> {
    let backup_id = crate::core::backup::create_backup()?;

    let pbkdf2_hash = crate::core::crypto::hash_password_pbkdf2(password);
    let fingerprint = crate::core::fingerprint::generate_fingerprint();
    let auth_token = crate::core::crypto::generate_auth_token(password, &fingerprint);

    let lock_result = (|| -> Result<(), String> {
        crate::core::usb::format_usb(device)?;
        crate::core::usb::write_auth_data(device, &auth_token, &fingerprint)?;
        write_machine_cfg(&fingerprint)?;

        write_superuser_config(&pbkdf2_hash)?;
        let usb_uuid = write_usb_check_script(device, &auth_token)?;

        crate::core::update_guard::install_guard()?;
        protect_menu_entries()?;
        run_update_grub()?;

        save_state(&usb_uuid, &pbkdf2_hash)?;
        Ok(())
    })();

    match lock_result {
        Ok(()) => Ok(()),
        Err(e) => {
            let _ = rollback_lock();
            Err(format!("{} (rollback attempted; backup: {})", e, backup_id))
        }
    }
}

/// Unlock GRUB — remove all protection and restore defaults
pub fn unlock_grub(password: &str) -> Result<(), String> {
    // Verify password first
    let state_path = Path::new(GRUBST_STATE_DIR).join(STATE_FILE);
    if state_path.exists() {
        let content = fs::read_to_string(&state_path)
            .map_err(|e| format!("Failed to read state: {}", e))?;
        let state: serde_json::Value = serde_json::from_str(&content)
            .map_err(|e| format!("Failed to parse state: {}", e))?;

        if let Some(hash) = state.get("password_hash").and_then(|v| v.as_str()) {
            if !crate::core::crypto::verify_password_pbkdf2(password, hash) {
                return Err("Invalid password".to_string());
            }
        } else {
            return Err("No password hash found in state".to_string());
        }
    }

    // Remove GRUBST scripts
    let superuser_path = Path::new(GRUBST_CONFIG_DIR).join(SUPERUSER_SCRIPT);
    let usb_check_path = Path::new(GRUBST_CONFIG_DIR).join(USB_CHECK_SCRIPT);
    let guard_path = Path::new(GRUBST_CONFIG_DIR).join("99_grubst_guard");

    if superuser_path.exists() {
        fs::remove_file(&superuser_path)
            .map_err(|e| format!("Failed to remove superuser script: {}", e))?;
    }
    if usb_check_path.exists() {
        fs::remove_file(&usb_check_path)
            .map_err(|e| format!("Failed to remove USB check script: {}", e))?;
    }
    if guard_path.exists() {
        fs::remove_file(&guard_path)
            .map_err(|e| format!("Failed to remove guard script: {}", e))?;
    }

    let machine_cfg = Path::new(GRUBST_GRUB_DIR).join(GRUBST_MACHINE_CFG);
    if machine_cfg.exists() {
        fs::remove_file(&machine_cfg)
            .map_err(|e| format!("Failed to remove machine cfg: {}", e))?;
    }

    // Restore backup if available
    let _ = crate::core::backup::restore_backup();

    // Update state
    if state_path.exists() {
        fs::remove_file(&state_path)
            .map_err(|e| format!("Failed to remove state file: {}", e))?;
    }

    // Regenerate GRUB config
    run_update_grub()?;

    log::info!("GRUB unlocked successfully");
    Ok(())
}

/// Save GRUBST state to disk
fn save_state(usb_uuid: &str, password_hash: &str) -> Result<(), String> {
    fs::create_dir_all(GRUBST_STATE_DIR)
        .map_err(|e| format!("Failed to create state dir: {}", e))?;

    let unrestricted_in_10_linux = Path::new(GRUBST_CONFIG_DIR)
        .join("10_linux")
        .exists()
        && fs::read_to_string(Path::new(GRUBST_CONFIG_DIR).join("10_linux"))
            .map(|c| c.contains("--unrestricted"))
            .unwrap_or(false);

    let state = serde_json::json!({
        "locked": true,
        "locked_at": chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
        "usb_uuid": usb_uuid,
        "password_hash": password_hash,
        "guard_installed": Path::new(GRUBST_CONFIG_DIR).join("99_grubst_guard").exists(),
        "unrestricted_in_10_linux": unrestricted_in_10_linux,
        "version": "1.0.0",
    });

    let state_path = Path::new(GRUBST_STATE_DIR).join(STATE_FILE);
    fs::write(&state_path, serde_json::to_string_pretty(&state).unwrap())
        .map_err(|e| format!("Failed to write state: {}", e))?;

    Ok(())
}

fn rollback_lock() -> Result<(), String> {
    let superuser_path = Path::new(GRUBST_CONFIG_DIR).join(SUPERUSER_SCRIPT);
    let usb_check_path = Path::new(GRUBST_CONFIG_DIR).join(USB_CHECK_SCRIPT);
    let guard_path = Path::new(GRUBST_CONFIG_DIR).join("99_grubst_guard");
    let state_path = Path::new(GRUBST_STATE_DIR).join(STATE_FILE);
    let machine_cfg = Path::new(GRUBST_GRUB_DIR).join(GRUBST_MACHINE_CFG);

    let _ = fs::remove_file(&superuser_path);
    let _ = fs::remove_file(&usb_check_path);
    let _ = fs::remove_file(&guard_path);
    let _ = fs::remove_file(&state_path);
    let _ = fs::remove_file(&machine_cfg);

    let _ = crate::core::backup::restore_backup();
    let _ = run_update_grub();
    Ok(())
}

fn write_machine_cfg(fingerprint: &str) -> Result<(), String> {
    fs::create_dir_all(GRUBST_GRUB_DIR)
        .map_err(|e| format!("Failed to create GRUBST dir: {}", e))?;

    let machine_cfg = Path::new(GRUBST_GRUB_DIR).join(GRUBST_MACHINE_CFG);
    let content = format!("set grubst_machine_fp_internal=\"{}\"\n", fingerprint);
    fs::write(&machine_cfg, content)
        .map_err(|e| format!("Failed to write machine cfg: {}", e))?;
    Ok(())
}

/// Set a file as executable (chmod +x)
fn set_executable(path: &Path) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;
    let perms = fs::Permissions::from_mode(0o755);
    fs::set_permissions(path, perms)
        .map_err(|e| format!("Failed to set executable: {}", e))?;
    Ok(())
}
