use std::fs;
use std::path::Path;

/// Path for the update guard script
const GUARD_SCRIPT_PATH: &str = "/etc/grub.d/99_grubst_guard";

/// Install the update guard — a script that re-applies GRUBST protection
/// every time update-grub runs (e.g., after kernel updates)
pub fn install_guard() -> Result<(), String> {
    let script_content = r#"#!/bin/sh
# ═══════════════════════════════════════════════════════════════
# GRUBST — Update Guard
# This script is auto-generated by GRUBST. DO NOT EDIT MANUALLY.
#
# Purpose: Detects whether GRUBST protection components are still
# present after `update-grub` / kernel updates, and emits warnings
# when something looks missing or modified.
# ═══════════════════════════════════════════════════════════════

GRUBST_USERS="/etc/grub.d/01_grubst_users"
GRUBST_USBCHECK="/etc/grub.d/02_grubst_usbcheck"
GRUBST_STATE="/var/lib/grubst/state.json"
GRUBST_MACHINE_CFG="/boot/grub/grubst/machine.cfg"
GRUBST_10_LINUX="/etc/grub.d/10_linux"
LOG_FILE="/var/log/grubst_guard.log"

log_event() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [GRUBST-GUARD] $1" >> "$LOG_FILE"
}

if [ ! -f "$GRUBST_STATE" ]; then
    exit 0
fi

# Verify critical files still exist and are executable
MISSING=""
ISSUES=""

if [ ! -f "$GRUBST_USERS" ]; then
    MISSING="$MISSING 01_grubst_users"
else
    if [ ! -x "$GRUBST_USERS" ]; then
        chmod 755 "$GRUBST_USERS" 2>/dev/null || true
        if [ ! -x "$GRUBST_USERS" ]; then
            ISSUES="$ISSUES 01_grubst_users_not_executable"
        fi
    fi
fi

if [ ! -f "$GRUBST_USBCHECK" ]; then
    MISSING="$MISSING 02_grubst_usbcheck"
else
    if [ ! -x "$GRUBST_USBCHECK" ]; then
        chmod 755 "$GRUBST_USBCHECK" 2>/dev/null || true
        if [ ! -x "$GRUBST_USBCHECK" ]; then
            ISSUES="$ISSUES 02_grubst_usbcheck_not_executable"
        fi
    fi
fi

if [ ! -f "$GRUBST_MACHINE_CFG" ]; then
    MISSING="$MISSING machine.cfg"
fi

if [ -f "$GRUBST_10_LINUX" ]; then
    if ! grep -q -- "--unrestricted" "$GRUBST_10_LINUX" 2>/dev/null; then
        ISSUES="$ISSUES 10_linux_missing_unrestricted"
    fi
fi

if [ -n "$MISSING" -o -n "$ISSUES" ]; then
    if [ -n "$MISSING" ]; then
        log_event "WARNING: GRUBST components missing:$MISSING"
    fi
    if [ -n "$ISSUES" ]; then
        log_event "WARNING: GRUBST components have issues:$ISSUES"
    fi
    log_event "Protection may have been reduced due to tampering or a system update."
    log_event "Run 'sudo grubst' to review status and re-apply protection if needed."

    # Write a warning visible at boot
    cat << 'GRUBST_GUARD_WARN_EOF'
# ═══════════════════════════════════════════
# ⚠️  GRUBST GUARD WARNING
# Some GRUBST protection components are missing or inconsistent.
# Run 'sudo grubst' to review status and re-apply protection.
# ═══════════════════════════════════════════
GRUBST_GUARD_WARN_EOF
else
    log_event "OK: GRUBST protection files verified after update-grub."
fi
"#;

    let script_path = Path::new(GUARD_SCRIPT_PATH);

    fs::write(script_path, script_content)
        .map_err(|e| format!("Failed to write guard script: {}", e))?;

    // Make executable
    use std::os::unix::fs::PermissionsExt;
    let perms = fs::Permissions::from_mode(0o755);
    fs::set_permissions(script_path, perms)
        .map_err(|e| format!("Failed to set guard permissions: {}", e))?;

    log::info!("Update guard installed: {}", GUARD_SCRIPT_PATH);
    Ok(())
}

/// Remove the update guard
pub fn remove_guard() -> Result<(), String> {
    let script_path = Path::new(GUARD_SCRIPT_PATH);

    if script_path.exists() {
        fs::remove_file(script_path)
            .map_err(|e| format!("Failed to remove guard script: {}", e))?;
        log::info!("Update guard removed");
    }

    Ok(())
}

/// Check if the update guard is installed
pub fn is_guard_installed() -> bool {
    Path::new(GUARD_SCRIPT_PATH).exists()
}
